services:
  Alengo\Bundle\AlengoFormBundle\Controller\Admin\FormDataController:
    tags: [ 'controller.service_arguments', { name: 'sulu.context', context: 'admin' } ]
    arguments:
      [ '@fos_rest.view_handler.default', '@security.token_storage', '@sulu_core.list_builder.field_descriptor_factory', '@sulu_core.doctrine_list_builder_factory', '@sulu_core.doctrine_rest_helper', '@Alengo\Bundle\AlengoFormBundle\Repository\FormDataRepository', '@alengo_form.save_form' ]
  alengo_form.controller.website:
    autowire: true
    class: 'Alengo\Bundle\AlengoFormBundle\Controller\FormDataController'
    tags: [ 'controller.service_arguments','container.service_subscriber',{ name: 'sulu.context', context: 'website' } ]
