services:
  Alengo\Bundle\AlengoFormBundle\Service\SaveFormService:
    public: 'true'
    arguments:
      [ '@Alengo\Bundle\AlengoFormBundle\Repository\FormDataRepository' ]
  Alengo\Bundle\AlengoFormBundle\Repository\FormDataRepository:
    public: 'true'
    arguments:
      [ '@doctrine' ]
  Alengo\Bundle\AlengoFormBundle\Admin\FormDataAdmin:
    tags: [ 'sulu.admin', { name: 'sulu.context', context: 'admin' } ]
    arguments:
      [ '@sulu_admin.view_builder_factory' ]
  Alengo\Bundle\AlengoFormBundle\Controller\Admin\FormDataController:
    tags: [ 'controller.service_arguments', { name: 'sulu.context', context: 'admin' } ]
    arguments:
      ['@fos_rest.view_handler.default', '@security.token_storage', '@sulu_core.list_builder.field_descriptor_factory', '@sulu_core.doctrine_list_builder_factory', '@sulu_core.doctrine_rest_helper', '@Alengo\Bundle\AlengoFormBundle\Repository\FormDataRepository']
