services:
    _defaults:
        autowire: true
        autoconfigure: true

    Alengo\Bundle\AlengoFormBundle\Controller\Admin\FormDataController:
        tags: [ 'controller.service_arguments', { name: 'sulu.context', context: 'admin' } ]
        arguments:
            $viewHandler: '@fos_rest.view_handler.default'
            $fieldDescriptorFactory: '@sulu_core.list_builder.field_descriptor_factory'
            $listBuilderFactory: '@sulu_core.doctrine_list_builder_factory'
            $restHelper: '@sulu_core.doctrine_rest_helper'

    Alengo\Bundle\AlengoFormBundle\Controller\FormDataController:
        tags: [ 'controller.service_arguments', { name: 'sulu.context', context: 'website' } ]
