services:
    _defaults:
        autowire: true
        autoconfigure: true

    Alengo\Bundle\AlengoFormBundle\Repository\FormDataRepository:
        public: true
        tags: [ 'doctrine.repository_service' ]

    Alengo\Bundle\AlengoFormBundle\Entity\Factory\FormDataFactory:
        public: true

    Alengo\Bundle\AlengoFormBundle\Service\SaveFormService:
        public: true
        arguments:
            $defaultReceiverMail: '%env(resolve:DEFAULT_SENDER_MAIL)%'

    Alengo\Bundle\AlengoFormBundle\Service\SaveFormInterface:
        public: true
        alias: Alengo\Bundle\AlengoFormBundle\Service\SaveFormService

    Alengo\Bundle\AlengoFormBundle\Service\SendFormService:
        public: true
        arguments:
            $defaultSenderName: '%env(resolve:DEFAULT_SENDER_NAME)%'
            $defaultSenderMail: '%env(resolve:DEFAULT_SENDER_MAIL)%'

    Alengo\Bundle\AlengoFormBundle\Service\SendFormInterface:
        public: true
        alias: Alengo\Bundle\AlengoFormBundle\Service\SendFormService

    Alengo\Bundle\AlengoFormBundle\Service\FormDataService:
        public: true

    Alengo\Bundle\AlengoFormBundle\Service\FormDataInterface:
        public: true
        alias: Alengo\Bundle\AlengoFormBundle\Service\FormDataService

    Alengo\Bundle\AlengoFormBundle\Admin\FormDataAdmin:
        tags: [ 'sulu.admin', { name: 'sulu.context', context: 'admin' } ]

    Alengo\Bundle\AlengoFormBundle\Preview\FormDataObjectProvider:
        public: true
        tags:
            - { name: 'sulu_preview.object_provider', provider-key: 'formData' }

    Alengo\Bundle\AlengoFormBundle\Routing\FormDataRouteDefaultsProvider:
        public: true
        tags:
            - { name: 'sulu_route.defaults_provider' }

    # Legacy aliases for backwards compatibility
    alengo_form.save_form:
        alias: Alengo\Bundle\AlengoFormBundle\Service\SaveFormInterface
        public: true

    alengo_form.send_form:
        alias: Alengo\Bundle\AlengoFormBundle\Service\SendFormInterface
        public: true

    alengo_form.form_data:
        alias: Alengo\Bundle\AlengoFormBundle\Service\FormDataInterface
        public: true
